<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20240325121122 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Time to make the donuts';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE note (
          title VARCHAR(255) NOT NULL,
          content TEXT DEFAULT NULL,
          id UUID NOT NULL,
          owner_id UUID NOT NULL,
          PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX IDX_CFBDFA147E3C61F9 ON note (owner_id)');
        $this->addSql('CREATE TABLE task (
          name VARCHAR(255) NOT NULL,
          github JSON NOT NULL,
          id UUID NOT NULL,
          todo_list_id UUID NOT NULL,
          PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX IDX_527EDB25E8A7DCFA ON task (todo_list_id)');
        $this->addSql('CREATE TABLE time_entry (
          started_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
          accumulated_time INT NOT NULL,
          running BOOLEAN NOT NULL,
          last_restarted_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT NULL,
          name VARCHAR(255) NOT NULL,
          id UUID NOT NULL,
          owner_id UUID NOT NULL,
          PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX IDX_6E537C0C7E3C61F9 ON time_entry (owner_id)');
        $this->addSql('CREATE TABLE todo_list (
          name VARCHAR(255) NOT NULL,
          id UUID NOT NULL,
          owner_id UUID NOT NULL,
          PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX IDX_1B199E077E3C61F9 ON todo_list (owner_id)');
        $this->addSql('CREATE TABLE "user" (
          display_name VARCHAR(180) NOT NULL,
          username VARCHAR(180) NOT NULL,
          PASSWORD VARCHAR(255) NOT NULL,
          roles JSON NOT NULL,
          git_hub_token JSON DEFAULT NULL,
          id UUID NOT NULL,
          PRIMARY KEY(id)
        )');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (username, display_name)');
        $this->addSql('CREATE TABLE messenger_messages (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          body TEXT NOT NULL,
          headers TEXT NOT NULL,
          queue_name VARCHAR(190) NOT NULL,
          created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
          available_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
          delivered_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT NULL,
          PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('CREATE TABLE rememberme_token (
          series VARCHAR(88) NOT NULL,
          value VARCHAR(88) NOT NULL,
          lastUsed TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
          class VARCHAR(100) NOT NULL,
          username VARCHAR(200) NOT NULL,
          PRIMARY KEY(series)
        )');
        $this->addSql('ALTER TABLE
          note
        ADD
          CONSTRAINT FK_CFBDFA147E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE
          task
        ADD
          CONSTRAINT FK_527EDB25E8A7DCFA FOREIGN KEY (todo_list_id) REFERENCES todo_list (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE
          time_entry
        ADD
          CONSTRAINT FK_6E537C0C7E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE
          todo_list
        ADD
          CONSTRAINT FK_1B199E077E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE note DROP CONSTRAINT FK_CFBDFA147E3C61F9');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB25E8A7DCFA');
        $this->addSql('ALTER TABLE time_entry DROP CONSTRAINT FK_6E537C0C7E3C61F9');
        $this->addSql('ALTER TABLE todo_list DROP CONSTRAINT FK_1B199E077E3C61F9');
        $this->addSql('DROP TABLE note');
        $this->addSql('DROP TABLE task');
        $this->addSql('DROP TABLE time_entry');
        $this->addSql('DROP TABLE todo_list');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('DROP TABLE rememberme_token');
    }
}
